"""userテーブル作成

Revision ID: 919054befd93
Revises: c464d19ad927
Create Date: 2026-10-08 21:33:42.738580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '919054befd93'
down_revision = 'c464d19ad927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
